version: '3.7'

services:
  selenium-hub:
    restart: always
    image: selenium/hub:latest
    container_name: Selenium_Hub    
    ports:
      - "4444:4444"

  #selenium-chrome
  selenium-chrome:
    restart: always
    image: selenium/node-chrome
    volumes:
      - /div/shm:/dev/shm
    depends_on:
      - selenium-hub
    environment:
      - HUB_HOST=selenium-hub
      - HUB_PORT=4444

  #selenium-firefox
  selenium-firefox:
    restart: always
    image: selenium/node-firefox
    volumes:
      - /div/shm:/dev/shm
    depends_on:
      - selenium-hub
    environment:
      - HUB_HOST=selenium-hub
      - HUB_PORT=4444
#docker-compose scale selenium-chrome=3 selenium-firefox=3
#docker-compose down
#entrypoint: tail -f /dev/null
